# Generated by Django 3.2.4 on 2021-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_diarist_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarist',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
